
# Comparing spatial models requires different approaches

---
  
```{r}
y <- x <- seq(1, 100)
x <- x + (1 * rnorm(100, 3))
y <- y + (1 * rnorm(100, 6, 6)) + (sqrt(y) * 2)
df <- data.frame(x, y)

df |> 
  ggplot(aes(x, y)) + 
  geom_point() + 
  theme_minimal() + 
  theme(
    panel.grid = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none",
    axis.title = element_text(size = 16),
    axis.line = element_line(linewidth = 1)
  ) + 
  labs(y = "Map 2", x = "Map 1")
```

---
  
```{r}
df |> 
  ggplot(aes(x, y)) + 
  geom_abline(slope = 1, intercept = 0, linewidth = 1) + 
  geom_point() + 
  theme_minimal() + 
  theme(
    panel.grid = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none",
    axis.title = element_text(size = 16),
    axis.line = element_line(linewidth = 1)
  ) + 
  labs(y = "Map 2", x = "Map 1")
```

---
  
```{r}
gmfr <- waywiser:::gmfr(y, x)

df |> 
  ggplot(aes(x, y)) + 
  geom_abline(slope = 1, intercept = 0, linewidth = 1) + 
  geom_point() + 
  geom_abline(slope = gmfr$b, intercept = gmfr$a, color = "forestgreen", linewidth = 1) + 
  theme_minimal() + 
  theme(
    panel.grid = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none",
    axis.title = element_text(size = 16),
    axis.line = element_line(linewidth = 1)
  ) + 
  labs(y = "Map 2", x = "Map 1")
```

